# Generated by Django 4.1.4 on 2023-01-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthorDeatils",
            fields=[
                ("Author_id", models.AutoField(primary_key=True, serialize=False)),
                ("AuthorName", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PublicationDetails",
            fields=[
                ("Pub_id", models.AutoField(primary_key=True, serialize=False)),
                ("PubName", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="BookDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BookName", models.CharField(max_length=60)),
                ("Launch_Year", models.PositiveIntegerField()),
                ("Desc", models.TextField()),
                (
                    "Author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.authordeatils",
                    ),
                ),
                (
                    "Pub_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.publicationdetails",
                    ),
                ),
            ],
        ),
    ]
