# Generated by Django 4.1.4 on 2023-01-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookdetails",
            name="Genre",
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
